//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMapping
    {
        public System.Guid Id { get; set; }
        public System.Guid PdfTemplateId { get; set; }
        public string PdfFieldName { get; set; }
        public int PdfPageNumber { get; set; }
        public string FieldType { get; set; }
        public Nullable<double> Left { get; set; }
        public Nullable<double> Right { get; set; }
        public Nullable<double> Top { get; set; }
        public Nullable<double> Bottom { get; set; }
        public string DbFieldName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryIP { get; set; }
        public string EntryId { get; set; }
    
        public virtual PdfTemplate PdfTemplate { get; set; }
    }
}
