//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialInformation
    {
        public System.Guid Id { get; set; }
        public System.Guid PdfTemplateId { get; set; }
        public string UserId { get; set; }
        public bool CourtOrTribunalOrder { get; set; }
        public string CourtFileNumber { get; set; }
        public string NameOfCourt { get; set; }
        public Nullable<int> DateOfCourtOrderDay { get; set; }
        public Nullable<int> DateOfCourtOrderMonth { get; set; }
        public Nullable<int> DateOfCourtOrderYear { get; set; }
        public string NameOfPersonWhoSuedYou { get; set; }
        public string AddressCourtTribunal { get; set; }
        public bool SheriffDirected { get; set; }
        public string WritNumber { get; set; }
        public string NameOfSherrif { get; set; }
        public string AddressOfSheriff { get; set; }
        public bool LiensOrSecurityInterests { get; set; }
        public string LiensOrSecurityInterestsNameOfPerson { get; set; }
        public string AmountOfMoneyOwed { get; set; }
        public string RegitrationNumber { get; set; }
        public bool FinancialStatementsRegistered { get; set; }
        public string FinancialStatementsRegitrationNumber { get; set; }
        public bool UndischargedBankrupt { get; set; }
        public string DetailsOfBankruptcy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryIP { get; set; }
        public string EntryId { get; set; }
    }
}
