//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class old_State
    {
        public long Srno { get; set; }
        public string StateId { get; set; }
        public string StateName { get; set; }
        public string Country { get; set; }
        public bool IsActive { get; set; }
    }
}
