//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInformation
    {
        public System.Guid Id { get; set; }
        public System.Guid PdfTemplateId { get; set; }
        public string UserId { get; set; }
        public string PresentFirstName { get; set; }
        public string PresentMiddleName { get; set; }
        public string PresentLastName { get; set; }
        public string Sex { get; set; }
        public string MailAddStreetNo { get; set; }
        public string MailAddPOBox { get; set; }
        public string MailAddAptSuitNo { get; set; }
        public string MailAddBuzzerNo { get; set; }
        public string MailAddCityTownVillage { get; set; }
        public string MailAddProvience { get; set; }
        public string MailAddPostalCode { get; set; }
        public string MailAddHomePhoneCode { get; set; }
        public string MailAddHomePhoneNo { get; set; }
        public string MailAddWorkPhoneCode { get; set; }
        public string MailAddWorkPhoneNo { get; set; }
        public Nullable<int> LivedInOntarioYears { get; set; }
        public Nullable<int> LivedInOntarioMonths { get; set; }
        public string LivedInOntarioPast12Months { get; set; }
        public Nullable<int> DOBYear { get; set; }
        public Nullable<int> DOBMonth { get; set; }
        public Nullable<int> DOBDay { get; set; }
        public string BirthCityTownVillage { get; set; }
        public string BirthProvinceOrState { get; set; }
        public string BirthCountry { get; set; }
        public string NewFirstName { get; set; }
        public string NewMiddleName { get; set; }
        public string NewLastName { get; set; }
        public string Married { get; set; }
        public string PartnerFisrtName { get; set; }
        public string PartnerMiddleName { get; set; }
        public string PartnerLastName { get; set; }
        public Nullable<int> DateMarriedMonth { get; set; }
        public Nullable<int> DateMarriedDay { get; set; }
        public Nullable<int> DateMarriedYear { get; set; }
        public string CityTownMarried { get; set; }
        public string StateOrProvinceMarried { get; set; }
        public string CountryMarried { get; set; }
        public string JDeclarationSigned { get; set; }
        public string JDeclarationPersonFirstName { get; set; }
        public string JDeclarationPersonMiddleName { get; set; }
        public string JDeclarationPersonLastName { get; set; }
        public Nullable<int> SentRegistrarMonth { get; set; }
        public Nullable<int> SentRegistrarDay { get; set; }
        public Nullable<int> SentRegistrarYear { get; set; }
        public string SubmittedForm4 { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryIP { get; set; }
        public string EntryId { get; set; }
    
        public virtual PdfTemplate PdfTemplate { get; set; }
    }
}
