//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriminalOffenceInformation
    {
        public System.Guid Id { get; set; }
        public System.Guid PdfFormTemplateId { get; set; }
        public string UserId { get; set; }
        public bool OutstandingCourtProceedings { get; set; }
        public string CourtFileNumber { get; set; }
        public string CourtName { get; set; }
        public string CourtAddress { get; set; }
        public string DescribeProceedings { get; set; }
        public bool OutstandingEnforcementOrders { get; set; }
        public string DetailsOfOutstandingEnforcementOrders { get; set; }
        public bool EverConvictedOfCriminalOffence { get; set; }
        public string DetailsOfCriminalOffence { get; set; }
        public bool FoundGuiltyDischarged { get; set; }
        public string FoundGuiltyDetailsOfOffence { get; set; }
        public bool AdultSentenceImposed { get; set; }
        public string DescribeAdultSentence { get; set; }
        public bool PendingCharges { get; set; }
        public string PendingChargesCourtNumber { get; set; }
        public string PendingChargesCourtName { get; set; }
        public string PendingChargesCourtAddress { get; set; }
        public string PendingChargesDescribe { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryIP { get; set; }
        public string EntryId { get; set; }
    
        public virtual PdfFormTemplate PdfFormTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
