//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormInfo
    {
        public System.Guid Id { get; set; }
        public System.Guid PdfFormTemplateId { get; set; }
        public System.Guid FormSectionId { get; set; }
    
        public virtual FormSection FormSection { get; set; }
        public virtual PdfFormTemplate PdfFormTemplate { get; set; }
    }
}
