//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameChangeInformation
    {
        public System.Guid Id { get; set; }
        public System.Guid PdfFormTemplateId { get; set; }
        public string UserId { get; set; }
        public string ResonForNameChange { get; set; }
        public string ChangedNamePriviously { get; set; }
        public Nullable<int> PreviousNameChangeDay { get; set; }
        public Nullable<int> PreviousNameChangeMonth { get; set; }
        public Nullable<int> PreviousNameChangeYear { get; set; }
        public string PreviousFirstName { get; set; }
        public string PreviousMiddleName { get; set; }
        public string PreviousLastName { get; set; }
        public string FirstNameAfterChange { get; set; }
        public string MiddleNameAfterChange { get; set; }
        public string LastNameAfterChange { get; set; }
        public string PreviousNameChangeProvince { get; set; }
        public string PreviousNameChangeCountry { get; set; }
        public Nullable<bool> AppliedForChangeAndRefused { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryIP { get; set; }
        public string EntryId { get; set; }
    
        public virtual PdfFormTemplate PdfFormTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
