//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nChanger.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PdfFormTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PdfFormTemplate()
        {
            this.FieldMappings = new HashSet<FieldMapping>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProvinceCategoryId { get; set; }
        public string TemplateName { get; set; }
        public string PdfFileName { get; set; }
        public string Comments { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryIP { get; set; }
        public string EntryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldMapping> FieldMappings { get; set; }
        public virtual ProvinceCategory ProvinceCategory { get; set; }
    }
}
